---
title: "Project"
author: "Travis Benedict"
date: "October 30, 2018"
output: pdf_document
---
```{r echo=TRUE}
library(magrittr)
library(dplyr)
library(mclust)
library(VGAM)
library(mapproj)
library(ggmap)
library(ggplot2)
library(maps)
library(mapdata)
library(choroplethr)
library(choroplethrMaps)
library(glmnet)
library(ROCR)
library(pROC)
library(mlbench)

set.seed(1)
```


#Format Data
```{r echo=TRUE}

# Predictors are separated from vote results join on FIPS
results = read.csv('CountyLevelResults.csv')
facts = read.csv('county_facts.csv')
descriptions = read.csv('county_facts_dictionary.csv')

###Point Diff Column Calculation
results$points_diff_rep = ((results$votes_dem - results$votes_gop)/results$total_votes)*-1


###Lean Calculation
results$Lean <- cut(results$points_diff_rep, 
                       breaks = c(-1, -.34, -.12, -.07, -.04, .04, .07, .12, .34, 1), 
                       labels = c("Solid Democratic", "Likely Democratic", "Lean Democratic", "Tilt Democratic", "Toss-Up", "Tilt GOP", "Lean GOP", "Likely GOP", "Solid GOP"), 
                       right = FALSE)
results$Lean_Number <- as.numeric(results$Lean)


###Winner Calculation
results$Winner <- cut(results$points_diff_rep, 
                       breaks = c(-1, 0, 1), 
                       labels = c("Democratic", "Republican"), 
                       right = FALSE)
results$Winner_Number <- as.numeric(results$Winner)

# Remove rows without results and identifier columns

joined_facts_results = merge(facts, results[c("combined_fips", "Lean", "Lean_Number", "points_diff_rep", "Winner", "Winner_Number")], by.x="Fips", by.y="combined_fips")
head(joined_facts_results)

cleaned_facts = data.frame(joined_facts_results[c(-1, -2, -3, -length(joined_facts_results[1,]), -(length(joined_facts_results[1,])-1), -(length(joined_facts_results[1,])-2), -(length(joined_facts_results[1,])-3), -(length(joined_facts_results[1,])-4), -(length(joined_facts_results[1,])-5), -(length(joined_facts_results[1,])-6))])

scaled_facts = scale(cleaned_facts)
```


# Exploratory Data Visualizations
```{r, echo=TRUE}

ggplot(cleaned_facts, aes(x=log10(PST045214))) + geom_histogram() + ggtitle("County Population") + scale_x_continuous(name="log10 Population") + scale_y_continuous(name="Count")

ggplot(cleaned_facts, aes(x=RHI125214)) + geom_histogram() + ggtitle("Percentage of White Population by County") + scale_x_continuous(name="Percent") + scale_y_continuous(name="Count")

ggplot(cleaned_facts, aes(x=EDU685213)) + geom_histogram() + ggtitle("Percentage of People 25+ with Bachelor's Degrees or Higher") + scale_x_continuous(name="Percent") + scale_y_continuous(name="Count")

```

#Maps
```{r echo=TRUE}
###Political Lean by County (State and County Outline)
colors = c("#0000ff", "#2020df", "#4040bf", "#60609f", "#808080", "#9f6060", "#bf4040", "#df2020", "#ff0000")
colorsmatched <- joined_facts_results$Lean_Number[match(county.fips$fips, joined_facts_results$Fips)]

map("county", col = colors[colorsmatched], fill = TRUE, resolution = 0, 
    lty = 0, projection = "polyconic")
# Add border around each State
map("county", col = "white", fill = FALSE, add = TRUE, lty = 1, lwd = .3, 
    projection = "polyconic")
map("state", col = "white", fill = FALSE, add = TRUE, lty = 1, lwd = .8, 
    projection = "polyconic")
title("Political Lean")
leg.txt <- c("Solid Democratic", "Likely Democratic", "Lean Democratic", "Tilt Democratic", "Toss-Up", "Tilt GOP", "Lean GOP", "Likely GOP", "Solid GOP")
legend("top", leg.txt, horiz = TRUE, fill = colors, cex=.35)


###Winner by County (State and County Outline)
colors = c("#0000ff", "#ff0000")
colorsmatched <- joined_facts_results$Winner_Number[match(county.fips$fips, joined_facts_results$Fips)+1]

map("county", col = colors[colorsmatched], fill = TRUE, resolution = 0, 
    lty = 0, projection = "polyconic")
# Add border around each State
map("county", col = "white", fill = FALSE, add = TRUE, lty = 1, lwd = .3, 
    projection = "polyconic")
map("state", col = "white", fill = FALSE, add = TRUE, lty = 1, lwd = .8, 
    projection = "polyconic")
title("Political Lean")
leg.txt <- c("Democratic", "Republican")
legend("top", leg.txt, horiz = TRUE, fill = colors, cex=.5)


#Demographic Maps

#Percent Non-Hispanic White
FIPS_White <- joined_facts_results %>% select(region=Fips, value=RHI825214)
county_choropleth(FIPS_White,
                  title ="2016 County Percent Non-Hispanic White", 
                 legend = "Percent Non-Hispanic White")

#Percent College Degree
FIPS_College_Degree <- joined_facts_results %>% select(region=Fips, value=EDU685213)
county_choropleth(FIPS_College_Degree,
                  title ="2016 County Percent College Degree", 
                 legend = "Percent College Degree")

#Per Capita Income
FIPS_PCI <- joined_facts_results %>% select(region=Fips, value=INC910213)
county_choropleth(FIPS_PCI,
                  title ="2016 County Per Capita Income", 
                 legend = "Per Capita Income")


###Political Lean by County (State and County Outline)
# usa <- map_data("usa")
# states <- map_data("state")
# county <- map_data("county")
# 
# 
# ggplot(data = county) + 
#   geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
#   coord_fixed(1.3) +
#   guides(fill=FALSE)  # do this to leave off the color legend
# 
# 
# 
# 
# 
# 
# 
# 
# map("county", fill = TRUE, resolution = 0, 
#     lty = 0, projection = "polyconic") + scale_fill_gradient(trans = "log10")
# 
# 
# 
# # counties <- map_data("county")
# # USA_counties <- ggplot(data = counties, mapping = aes(x = long, y = lat, group = group)) + 
# #   coord_fixed(1.3) + 
# #   geom_polygon(color = "black", fill = "gray")
# # 
# # USA_counties + geom_polygon(data = cleaned_facts, aes(fill = RHI825214), color = "white")
# # 
# # cleaned_facts %>%
# #   ggplot(aes(long, lat, group = group, fill = RHI825214)) +
# #   geom_polygon(color = NA) +
# #   coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
# #   labs(fill = "Median Household Income")
# # 
# # 
# # cleaned_facts %>%
# #   ggplot(aes(long, lat, group = group, fill = RHI825214)) +
# #   geom_polygon(color = NA) +
# #   scale_fill_gradientn(labels = scales::percent,
# #                        guide = guide_colorbar(title.position = "top")) +
# #   geom_polygon(data = states, mapping = aes(long, lat, group = group),
# #                fill = NA, color = "#ffffff") +
# #   coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
# #   theme(legend.title = element_text(),
# #         legend.key.width = unit(.5, "in")) +
# #   labs(fill = "Homeownership rate") +
# #   theme_urban_map()
# # 
# # df1 <- joined_facts_results %>% select(subregion=County, region=State, B20004001 )
# # 
# # 
# # ggplot(cleaned_facts, aes(long, lat,group = group)) + 
# #   geom_polygon(aes(fill = RHI825214), colour = rgb(1,1,1,0.2))  +
# #   coord_quickmap()

```



#Principal Component Analysis
```{r echo=TRUE}
#########PCA
prin_comp <- prcomp(scaled_facts, scale. = F)

pca <- summary(prin_comp)

#scree plot
plot(pca$importance[2,], xlab = "Principal Component",
             ylab = "Proportion of Variance Explained",
             type = "b")

#cumulative scree plot
plot(pca$importance[3,], xlab = "Principal Component",
              ylab = "Cumulative Proportion of Variance Explained",
              type = "b")
# abline(h=0.8)
abline(v=5)

# Data from first 17 principal components
pc_data <- prin_comp$x[,1:10]


# 
# autoplot(prin_comp, data = scaled_facts, colour = 'Lean', loadings = TRUE, loadings.colour = 'blue',
#          loadings.label = TRUE, loadings.label.size = 3) +
#   ggtitle("First two PC's using Original Variables")
# 
# 


```






# Logit Model Fitting
```{r, echo=TRUE}

# Fit a logit model with just non hispanic white and college dregree
joined_facts_results$GOPDem[joined_facts_results$points_diff_rep < 0] <- 0
joined_facts_results$GOPDem[joined_facts_results$points_diff_rep > 0] <- 1

y = joined_facts_results$GOPDem
x = scaled_facts
link = "logit"

# Train on 75% Test on 25%
testIndexes = sample(1:nrow(x), floor(0.25 * nrow(x)))

# PC FIT
# Use the first 17 PCs to fit the model
pc5_fit <- glm(y[-testIndexes] ~ ., data=data.frame(pc_data[-testIndexes,1:5]), family=binomial(link=link))
pc5_predicted <- predict(pc5_fit, data.frame(pc_data[testIndexes,]), type="response")
# Confusion Matrix
table(pred=ifelse(pc5_predicted > 0.5, 1, 0),true=y[testIndexes])

pc5_outcome = data.frame(cbind(y[testIndexes], predict(pc5_fit, data.frame(pc_data[testIndexes,1:5]), type="response")))
colnames(pc5_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
pc5_r = roc(Truth ~ Predicted, data = pc5_outcome)
plot(pc5_r, main = paste("First 5 PCs Model Auc:", round(auc(pc5_r), 3)))

# Use the first 10 PCs to fit the model
pc_fit <- glm(y[-testIndexes] ~ ., data=data.frame(pc_data[-testIndexes,]), family=binomial(link=link))
pc_predicted <- predict(pc_fit, data.frame(pc_data[testIndexes,]), type="response")
# Confusion Matrix
table(pred=ifelse(pc_predicted > 0.5, 1, 0),true=y[testIndexes])

pc_outcome = data.frame(cbind(y[testIndexes], predict(pc_fit, data.frame(pc_data[testIndexes,]), type="response")))
colnames(pc_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
pc_r = roc(Truth ~ Predicted, data = pc_outcome)
plot(pc_r, main = paste("First 10 PCs Model Auc:", round(auc(pc_r), 3)))

# FORWARD/BACKWARD AIC/BIC

# Perform forward and backward AIC/BIC variable selection
y = joined_facts_results$GOPDem
x = scaled_facts
link = "logit"
fit_full <- glm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes,]), 
                family=(binomial(link = link)))
fit_null <- glm(y[-testIndexes] ~ 1, data=data.frame(x[-testIndexes,]), family = binomial(link = "logit"))

# Forward AIC:
forAIC = step(fit_null,  # Start with NULL model
               scope = list(lower=fit_null, upper=fit_full), # Range of models
               direction="forward",
              trace = FALSE) # Forward or backward
faCoefficients = names(forAIC$coefficients)
faCoefficients = faCoefficients[faCoefficients != "(Intercept)"]

fa_outcome = data.frame(cbind(y[testIndexes], predict(forAIC, data.frame(x[testIndexes,]), type="response")))
colnames(fa_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
fa_r = roc(Truth ~ Predicted, data = fa_outcome)
plot(fa_r, main = paste("Forward AIC Model Auc:", round(auc(fa_r), 3)))


# Backward AIC:
backAIC = step(fit_full,  # Start with NULL model
               scope = list(lower=fit_null, upper=fit_full), # Range of models
               direction="backward",
              trace = FALSE) # Forward or backward
baCoefficients = names(backAIC$coefficients)
baCoefficients = baCoefficients[baCoefficients != "(Intercept)"]

ba_outcome = data.frame(cbind(y[testIndexes], predict(backAIC, data.frame(x[testIndexes,]), type="response")))
colnames(ba_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
ba_r = roc(Truth ~ Predicted, data = ba_outcome)
plot(ba_r, main = paste("Backward AIC Model Auc:", round(auc(ba_r), 3)))


# Forward BIC:
forBIC = step(fit_null,  # Start with NULL model
               scope = list(lower=fit_null, upper=fit_full), # Range of models
               direction="forward",
              k = log(length(y)),
              trace = FALSE) # Forward or backward
fbCoefficients = names(forBIC$coefficients)
fbCoefficients = fbCoefficients[fbCoefficients != "(Intercept)"]

fb_outcome = data.frame(cbind(y[testIndexes], predict(forBIC, data.frame(x[testIndexes,]), type="response")))
colnames(fb_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
fb_r = roc(Truth ~ Predicted, data = fb_outcome)
plot(fb_r, main = paste("Forward BIC Model Auc:", round(auc(fb_r), 3)))

# Backward BIC:
backBIC = step(fit_full,  # Start with NULL model
               scope = list(lower=fit_null, upper=fit_full), # Range of models
               direction="backward",
              k = log(length(y)),
              trace = FALSE) # Forward or backward
bbCoefficients = names(backBIC$coefficients)
bbCoefficients = bbCoefficients[bbCoefficients != "(Intercept)"]

bb_outcome = data.frame(cbind(y[testIndexes], predict(backBIC, data.frame(x[testIndexes,]), type="response")))
colnames(bb_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
bb_r = roc(Truth ~ Predicted, data = bb_outcome)
plot(bb_r, main = paste("Backward BIC Model Auc:", round(auc(bb_r), 3)))

# LASSO

#Perform grid search to find optimal value of lambda
#family= binomial => logistic regression, alpha=1 => lasso
cv.out <- cv.glmnet(x,y,alpha=1,family="binomial",type.measure = "auc" )
#plot result
plot(cv.out)

#Min value of lambda (Just interesting to compare to best value of Lambda)
lambda_min <- cv.out$lambda.min
#Best value of lambda
lambda_1se <- cv.out$lambda.1se


#Regression coefficients
lasso_coeff = colnames(x)[summary(coef(cv.out,s=lambda_1se))$i]
lasso_coeff = lasso_coeff[lasso_coeff != "(Intercept)"][!is.na(lasso_coeff)]

lasso_fit = glm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes,lasso_coeff]), 
                family=(binomial(link = link)))

lasso_outcome = data.frame(cbind(y[testIndexes], predict(lasso_fit, data.frame(x[testIndexes,]), type="response")))
colnames(lasso_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
lasso_r = roc(Truth ~ Predicted, data = lasso_outcome)
plot(lasso_r, main = paste("Lasso Model Auc:", round(auc(lasso_r), 3)))

# Count the number times each variable was selected
all_coeff_counts = sort(table(c(faCoefficients, baCoefficients, fbCoefficients, bbCoefficients, lasso_coeff)), decreasing = TRUE)







# Create a bar plot of coefficients and their counts
ggplot(data=data.frame(all_coeff_counts[all_coeff_counts > 2]), aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(x = "Variable", y = "Frequency of Selection")





# Create consensus model using variables chosen every time
consensus_coeff = names(all_coeff_counts[all_coeff_counts == 5])
consensus_coeff = consensus_coeff[consensus_coeff != "(Intercept)"]

consensus_fit = glm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes,consensus_coeff]), 
                family=(binomial(link = link)))
consensus_coeff

consensus_outcome = data.frame(cbind(y[testIndexes], predict(consensus_fit, data.frame(x[testIndexes,]), type="response")))
colnames(consensus_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
consensus_r = roc(Truth ~ Predicted, data = consensus_outcome)
plot(consensus_r, main = paste("Consensus Selected Coefficients Auc:", round(auc(consensus_r), 3)))

# Create majority model using variables chosen 4 or more times
majority_coeff = names(all_coeff_counts[all_coeff_counts > 3])
majority_coeff = consensus_coeff[consensus_coeff != "(Intercept)"]

majority_fit = glm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes,majority_coeff]), 
                family=(binomial(link = link)))
majority_coeff

majority_outcome = data.frame(cbind(y[testIndexes], predict(majority_fit, data.frame(x[testIndexes,]), type="response")))
colnames(majority_outcome) = c("Truth", "Predicted")

#Plot ROC Curve
majority_r = roc(Truth ~ Predicted, data = majority_outcome)
plot(majority_r, main = paste("4 or 5 Models Selected Coefficients Auc:", round(auc(majority_r), 3)))
```


# Cummulative Logit Fitting (Ordinal)
```{r, echo=TRUE}

y = as.numeric(joined_facts_results$Lean)

# Principal Components
pc_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(pc_data[-testIndexes, ]), 
                family=(cumulative(link="logit", parallel=TRUE)))

pc_prediction = predict(pc_ordinal, data.frame(pc_data[testIndexes, ]), type="response")
table(Expected=max.col(pc_prediction),Actual=joined_facts_results$Lean[testIndexes])

pc_outcome = data.frame(cbind(y[testIndexes], max.col(pc_prediction)))
colnames(pc_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
pc_r = roc(Truth ~ Predicted, data = pc_outcome)
plot(pc_r, main = paste("First 10 PCs Auc:", round(auc(pc_r), 3)))

# Forward AIC
fa_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, faCoefficients]), 
                family=(cumulative(link="logit", parallel=TRUE)))

fa_prediction = predict(fa_ordinal, data.frame(x[testIndexes, faCoefficients]), type="response")
table(Expected=max.col(fa_prediction),Actual=joined_facts_results$Lean[testIndexes])

fa_outcome = data.frame(cbind(y[testIndexes], max.col(fa_prediction)))
colnames(fa_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
fa_r = roc(Truth ~ Predicted, data = fa_outcome)
plot(fa_r, main = paste("Forward AIC Coefficients Auc:", round(auc(fa_r), 3)))

# Backward AIC
ba_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, baCoefficients]), 
                family=(cumulative(link="logit", parallel=TRUE)))

ba_prediction = predict(ba_ordinal, data.frame(x[testIndexes, baCoefficients]), type="response")
table(Expected=max.col(ba_prediction),Actual=joined_facts_results$Lean[testIndexes])

ba_outcome = data.frame(cbind(y[testIndexes], max.col(ba_prediction)))
colnames(ba_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
ba_r = roc(Truth ~ Predicted, data = ba_outcome)
plot(ba_r, main = paste("Backward AIC Coefficients Auc:", round(auc(ba_r), 3)))

# Forward BIC
fb_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, fbCoefficients]), 
                family=(cumulative(link="logit", parallel=TRUE)))

fb_prediction = predict(fb_ordinal, data.frame(x[testIndexes, fbCoefficients]), type="response")
table(Expected=max.col(fb_prediction),Actual=joined_facts_results$Lean[testIndexes])

fb_outcome = data.frame(cbind(y[testIndexes], max.col(fb_prediction)))
colnames(fb_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
fb_r = roc(Truth ~ Predicted, data = fb_outcome)
plot(fb_r, main = paste("Forward BIC Coefficients Auc:", round(auc(fb_r), 3)))

# Backward BIC
bb_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, bbCoefficients]), 
                family=(cumulative(link="logit", parallel=TRUE)))

bb_prediction = predict(bb_ordinal, data.frame(x[testIndexes, bbCoefficients]), type="response")
table(Expected=max.col(bb_prediction),Actual=joined_facts_results$Lean[testIndexes])

bb_outcome = data.frame(cbind(y[testIndexes], max.col(bb_prediction)))
colnames(bb_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
bb_r = roc(Truth ~ Predicted, data = bb_outcome)
plot(bb_r, main = paste("Backward BIC Coefficients Auc:", round(auc(bb_r), 3)))

# Lasso
lasso_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, lasso_coeff]), 
                family=(cumulative(link="logit", parallel=TRUE)))

lasso_prediction = predict(lasso_ordinal, data.frame(x[testIndexes, lasso_coeff]), type="response")
table(Expected=max.col(lasso_prediction),Actual=joined_facts_results$Lean[testIndexes])

lasso_outcome = data.frame(cbind(y[testIndexes], max.col(lasso_prediction)))
colnames(lasso_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
lasso_r = roc(Truth ~ Predicted, data = lasso_outcome)
plot(lasso_r, main = paste("Lasso Coefficients Auc:", round(auc(lasso_r), 3)))

# Consensus
consensus_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, consensus_coeff]), 
                family=(cumulative(link="logit", parallel=TRUE)))

consensus_prediction = predict(consensus_ordinal, data.frame(x[testIndexes, consensus_coeff]), type="response")
table(Expected=max.col(consensus_prediction),Actual=joined_facts_results$Lean[testIndexes])

consensus_outcome = data.frame(cbind(y[testIndexes], max.col(consensus_prediction)))
colnames(consensus_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
consensus_r = roc(Truth ~ Predicted, data = consensus_outcome)
plot(consensus_r, main = paste("Consensus Coefficients Auc:", round(auc(consensus_r), 3)))

# Majority
majority_ordinal <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, majority_coeff]), 
                family=(cumulative(link="logit", parallel=TRUE)))

majority_prediction = predict(majority_ordinal, data.frame(x[testIndexes, majority_coeff]), type="response")
table(Expected=max.col(majority_prediction),Actual=joined_facts_results$Lean[testIndexes])

majority_outcome = data.frame(cbind(y[testIndexes], max.col(majority_prediction)))
colnames(majority_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
majority_r = roc(Truth ~ Predicted, data = majority_outcome)
plot(majority_r, main = paste("4 or 5 Models Selected Coefficients Auc:", round(auc(majority_r), 3)))

```
# CHANGE VARIABLE NAMES FOR ALL BELOW


# Multinomial Logit Fitting
```{r, echo =TRUE}

y = as.numeric(joined_facts_results$Lean)

# First 10 PCs
pc_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(pc_data[-testIndexes, faCoefficients]), 
                family=(multinomial))

pc_prediction = predict(pc_multi, data.frame(pc_data[testIndexes, ]), type="response")
table(Expected=max.col(pc_prediction),Actual=joined_facts_results$Lean[testIndexes])

pc_outcome = data.frame(cbind(y[testIndexes], max.col(pc_prediction)))
colnames(pc_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
pc_r = roc(Truth ~ Predicted, data = pc_outcome)
plot(pc_r, main = paste("First 10 PCs Auc:", round(auc(pc_r), 3)))

# Forward AIC
fa_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, faCoefficients]), 
                family=(multinomial))

fa_prediction = predict(fa_multi, data.frame(x[testIndexes, faCoefficients]), type="response")
table(Expected=max.col(fa_prediction),Actual=joined_facts_results$Lean[testIndexes])

fa_outcome = data.frame(cbind(y[testIndexes], max.col(fa_prediction)))
colnames(fa_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
fa_r = roc(Truth ~ Predicted, data = fa_outcome)
plot(fa_r, main = paste("Forward AIC Coefficients Auc:", round(auc(fa_r), 3)))

# Backward AIC
ba_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, baCoefficients]), 
                family=(multinomial))

ba_prediction = predict(ba_multi, data.frame(x[testIndexes, baCoefficients]), type="response")
table(Expected=max.col(ba_prediction),Actual=joined_facts_results$Lean[testIndexes])

ba_outcome = data.frame(cbind(y[testIndexes], max.col(ba_prediction)))
colnames(ba_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
ba_r = roc(Truth ~ Predicted, data = ba_outcome)
plot(ba_r, main = paste("Backward AIC Coefficients Auc:", round(auc(ba_r), 3)))

# Forward BIC
fb_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, fbCoefficients]), 
                family=(multinomial))

fb_prediction = predict(fb_multi, data.frame(x[testIndexes, fbCoefficients]), type="response")
table(Expected=max.col(fb_prediction),Actual=joined_facts_results$Lean[testIndexes])

fb_outcome = data.frame(cbind(y[testIndexes], max.col(fb_prediction)))
colnames(fb_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
fb_r = roc(Truth ~ Predicted, data = fb_outcome)
plot(fb_r, main = paste("Forward BIC Coefficients Auc:", round(auc(fb_r), 3)))

# Backward BIC
bb_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, bbCoefficients]), 
                family=(multinomial))

bb_prediction = predict(bb_multi, data.frame(x[testIndexes, bbCoefficients]), type="response")
table(Expected=max.col(bb_prediction),Actual=joined_facts_results$Lean[testIndexes])

bb_outcome = data.frame(cbind(y[testIndexes], max.col(bb_prediction)))
colnames(bb_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
bb_r = roc(Truth ~ Predicted, data = bb_outcome)
plot(bb_r, main = paste("Backward BIC Coefficients Auc:", round(auc(bb_r), 3)))

# Lasso
lasso_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, lasso_coeff]), 
                family=(multinomial))

lasso_prediction = predict(lasso_multi, data.frame(x[testIndexes, lasso_coeff]), type="response")
table(Expected=max.col(lasso_prediction),Actual=joined_facts_results$Lean[testIndexes])

lasso_outcome = data.frame(cbind(y[testIndexes], max.col(lasso_prediction)))
colnames(lasso_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
lasso_r = roc(Truth ~ Predicted, data = lasso_outcome)
plot(lasso_r, main = paste("Lasso Coefficients Auc:", round(auc(lasso_r), 3)))

# Consensus
consensus_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, consensus_coeff]), 
                family=(multinomial))

consensus_prediction = predict(consensus_multi, data.frame(x[testIndexes, consensus_coeff]), type="response")
table(Expected=max.col(consensus_prediction),Actual=joined_facts_results$Lean[testIndexes])

consensus_outcome = data.frame(cbind(y[testIndexes], max.col(consensus_prediction)))
colnames(consensus_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
consensus_r = roc(Truth ~ Predicted, data = consensus_outcome)
plot(consensus_r, main = paste("Consensus Coefficients Auc:", round(auc(consensus_r), 3)))

# Majority
majority_multi <- vglm(y[-testIndexes] ~ ., data=data.frame(x[-testIndexes, majority_coeff]), 
                family=(multinomial))

majority_prediction = predict(majority_multi, data.frame(x[testIndexes, majority_coeff]), type="response")
table(Expected=max.col(majority_prediction),Actual=joined_facts_results$Lean[testIndexes])

majority_outcome = data.frame(cbind(y[testIndexes], max.col(majority_prediction)))
colnames(majority_outcome) = c("Truth", "Predicted")
#Plot ROC Curve
majority_r = roc(Truth ~ Predicted, data = majority_outcome)
plot(majority_r, main = paste("4 or 5 Models Selected Coefficients Auc:", round(auc(majority_r), 3)))
```




